Update mini bot
Frc5572/Jetsi-Offseason pull request #23
Opened 2023-01-16 23:16 UTC by ihernandez3647

2023-01-17 02:36 UTC, legoguy1000 requested changes
- Delete the Autos and associated files.  Leave the "Resnick Auto" as a place holder. (lines 37-39)
- Delete the `Ultrasonic()` and associated files. (lines 56, 970
- Update the `getAutonomousCommand()` method to be like https://github.com/Frc5572/FRC2022/blob/main/src/main/java/frc/robot/RobotContainer.java#L255

2023-01-17 02:36 UTC, legoguy1000 commented on src/main/java/frc/robot/RobotContainer.java
> +        s_Swerve.setDefaultCommand(new TeleopSwerve(s_Swerve, vision, driver,
lets get rid of the vision stuff.  No longer needed

2023-01-17 02:36 UTC, legoguy1000 commented on src/main/java/frc/robot/commands/TeleopSwerve.java
>          vision.update();
remove vision

2023-01-17 02:36 UTC, legoguy1000 commented on src/main/java/frc/robot/commands/TeleopSwerve.java
> +    public TeleopSwerve(Swerve s_Swerve, Vision vision, CommandXboxController controller,
remove vision

2023-01-17 02:36 UTC, legoguy1000 commented on src/main/java/frc/robot/commands/TeleopSwerve.java
>      private Vision vision;
remove vision

2023-01-17 02:36 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/Swerve.java
>          zeroGyro();
remove this

2023-01-17 02:36 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/Swerve.java
> +        // gyro.zeroYaw();
delete this line

2023-01-19 04:39 UTC, legoguy1000 requested changes
minor things then GTG

2023-01-19 04:39 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/Swerve.java
> +
Delete this

2023-01-19 04:39 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/Swerve.java
> +        swerveOdometry.update(new Rotation2d(yaw.getRadians()), getPositions());
`getYaw()` returns a `Rotation2d` so no reason to convert to radians and then back. `swerveOdometry.update(getYaw(), getPositions());` will work

2023-01-19 04:39 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/Swerve.java
> +    }
Not needed

2023-01-19 22:45 UTC, agrinmanriv0537 approved these changes

2023-01-19 22:59 UTC, legoguy1000 approved these changes
Looks GTG

2023-01-19 23:01 UTC, merged